In [4]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\Maxja\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Maxja\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Maxja\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Maxja\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Maxja\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
print(pd.__version__)

3.0.5

In [8]:
# Exercise 1: Create a Dataframe
data = {
    "trial_id":["NCT001", "NCT002", "NCT003"],
    "sponsor_name":["Pfizer", "AstraZeneca", "GSK"],
    "start_year":[2020, 2021, 2019],
}
df = pd.DataFrame(data)
print(df)

# data creates dictionary with three keys: trial_id, sponsor_name, and start_year. Each key has a list of values associated with it. The DataFrame is created using this dictionary, resulting in a tabular structure where each key becomes a column and the corresponding values become the rows of the DataFrame.

  trial_id sponsor_name  start_year
0   NCT001       Pfizer        2020
1   NCT002  AstraZeneca        2021
2   NCT003          GSK        2019

In [9]:
# Exercise 2: Inspecting a DataFrame
df.head()

  trial_id sponsor_name  start_year
0   NCT001       Pfizer        2020
1   NCT002  AstraZeneca        2021
2   NCT003          GSK        2019

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   trial_id      3 non-null      str
 1   sponsor_name  3 non-null      str
 2   start_year    3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [11]:
df.describe()

       start_year
count         3.0
mean       2020.0
std           1.0
min        2019.0
25%        2019.5
50%        2020.0
75%        2020.5
max        2021.0

In [12]:
#Exercise 3: Selecting Columns and Rows
df['sponsor_name']  # Selecting a single column

0         Pfizer
1    AstraZeneca
2            GSK
Name: sponsor_name, dtype: str

In [13]:
df[["trial_id", "start_year"]]  # Selecting multiple columns

  trial_id  start_year
0   NCT001        2020
1   NCT002        2021
2   NCT003        2019

In [14]:
#loc and iloc are two methods in pandas used for selecting data from a DataFrame, but they differ in how they access the data.
df.loc[0]  # Selecting a single row by label (index)

trial_id        NCT001
sponsor_name    Pfizer
start_year        2020
Name: 0, dtype: object

In [15]:
df.loc[0, "sponsor_name"]  # Selecting a single value by row and column labels

'Pfizer'

In [16]:
df.loc[0:1,["trial_id", "sponsor_name"]]  # Selecting multiple rows and columns by labels

  trial_id sponsor_name
0   NCT001       Pfizer
1   NCT002  AstraZeneca

In [17]:
df.iloc[0]  # Selecting a single row by integer position

trial_id        NCT001
sponsor_name    Pfizer
start_year        2020
Name: 0, dtype: object

In [18]:
df.iloc[0,1]  # Selecting a single value by row and column integer positions

'Pfizer'

In [ ]:
df.loc[0, "sponsor_name"]  # Selecting a single value by row and column labels

'Pfizer'

In [21]:
#Exercise 4: Filtering Rows
data = {
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "sponsor_name": ["Pfizer", "AstraZeneca", "GSK"],
    "start_year": [2020, 2021, 2019]
}

df = pd.DataFrame(data)

df[df["start_year"] >= 2020]

  trial_id sponsor_name  start_year
0   NCT001       Pfizer        2020
1   NCT002  AstraZeneca        2021

In [22]:
data = {
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "sponsor_name": ["Pfizer", "AstraZeneca", "GSK"],
    "start_year": [2020, 2021, 2019]
}

df = pd.DataFrame(data)

df[df["sponsor_name"]=="Pfizer"]

  trial_id sponsor_name  start_year
0   NCT001       Pfizer        2020

In [24]:
data = {
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "sponsor_name": ["Pfizer", "AstraZeneca", "GSK"],
    "start_year": [2020, 2021, 2019]
}

df = pd.DataFrame(data)

df[
    (df["sponsor_name"] == "Pfizer") |
    (df["sponsor_name"] == "GSK")
]

  trial_id sponsor_name  start_year
0   NCT001       Pfizer        2020
2   NCT003          GSK        2019

In [25]:
data = {
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "sponsor_name": ["Pfizer", "AstraZeneca", "GSK"],
    "start_year": [2020, 2021, 2019]
}

df = pd.DataFrame(data)

df[
    (df["start_year"] >= 2020) &
    (df["sponsor_name"] == "AstraZeneca")
]

  trial_id sponsor_name  start_year
1   NCT002  AstraZeneca        2021

In [27]:
# Exercise 5: Sorting Data
data = {
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "sponsor_name": ["Pfizer", "AstraZeneca", "GSK"],
    "start_year": [2020, 2021, 2019]
}

df = pd.DataFrame(data)

df.sort_values(
    ["start_year", "sponsor_name"],
    ascending=[False, True]
)

  trial_id sponsor_name  start_year
1   NCT002  AstraZeneca        2021
0   NCT001       Pfizer        2020
2   NCT003          GSK        2019

In [28]:
data = {
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "sponsor_name": ["Pfizer", "AstraZeneca", "GSK"],
    "start_year": [2020, 2021, 2019]
}

df = pd.DataFrame(data)

df.sort_values(
    "start_year", ascending=False)

  trial_id sponsor_name  start_year
1   NCT002  AstraZeneca        2021
0   NCT001       Pfizer        2020
2   NCT003          GSK        2019

In [ ]:
#Exercise 6: Dates
# real-clinical trials data will use full dates such as 2021-05-14

date_data={
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "start_date": ["2020-03-15", "2021-07-01", "2019-11-20"]
}
date_df=pd.DataFrame(date_data)
print(date_df)

date_df.info()

date_df["start_date"] = pd.to_datetime(date_df["start_date"])

date_df.info()
date_df["start_year"] = date_df["start_date"].dt.year
date_df["start_month"] = date_df["start_date"].dt.month

date_df

  trial_id  start_date
0   NCT001  2020-03-15
1   NCT002  2021-07-01
2   NCT003  2019-11-20
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   trial_id    3 non-null      str
 1   start_date  3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   trial_id    3 non-null      str
 1   start_date  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(1)
memory usage: 180.0 bytes

  trial_id start_date  start_year  start_month
0   NCT001 2020-03-15        2020            3
1   NCT002 2021-07-01        2021            7
2   NCT003 2019-11-20        2019           11

In [ ]:
#7 Exercise 7: Data Types

type_data = {
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "enrollment": ["120", "250", "180"],
    "industry_sponsored": [True, False, True]
}

type_df = pd.DataFrame(type_data)

type_df.info()
#enrollment is inside the quotes so it is being treated as a string (object) data type. To perform numerical operations on this column, we need to convert it to an integer data type.

type_df["enrollment"] = type_df["enrollment"].astype(int)
type_df.info()

print(type_df["enrollment"].dtype)

#key idea is that .astype(int) means convert this column into integer

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   trial_id            3 non-null      str
 1   enrollment          3 non-null      str
 2   industry_sponsored  3 non-null      bool
dtypes: bool(1), str(2)
memory usage: 183.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   trial_id            3 non-null      str
 1   enrollment          3 non-null      int64
 2   industry_sponsored  3 non-null      bool
dtypes: bool(1), int64(1), str(1)
memory usage: 183.0 bytes
int64

In [ ]:
#Exercise 8: Groupby

group_data = {
    "sponsor_name": ["Pfizer", "Pfizer", "GSK", "GSK", "AstraZeneca"],
    "enrollment": [120, 180, 200, 150, 250]
}

group_df = pd.DataFrame(group_data)

group_df

group_df.groupby("sponsor_name")["enrollment"].sum()

group_df.groupby("sponsor_name")["enrollment"].mean()
group_df.groupby("sponsor_name")["enrollment"].count()
group_df.groupby("sponsor_name", as_index=False)["enrollment"].sum()

#as_index keeps sponsor_name as a normal column which is easier to work with latr one

# give the average enrolment
group_df.groupby("sponsor_name", as_index=False)["enrollment"].mean()

  sponsor_name  enrollment
0  AstraZeneca       250.0
1          GSK       175.0
2       Pfizer       150.0

In [47]:
#Exercise 9: Merge

trials_df = pd.DataFrame({
    "trial_id": ["NCT001", "NCT002", "NCT003"],
    "sponsor_name": ["Pfizer", "GSK", "AstraZeneca"]
})

countries_df = pd.DataFrame({
    "trial_id": ["NCT001", "NCT002", "NCT004"],
    "country": ["United Kingdom", "United States", "France"]
})

merged_df = trials_df.merge(
    countries_df,
    on="trial_id",
    how="inner"
)

merged_df

# only returns NCT001 and NCT002 because they are the only trial_ids that exist in both DataFrames. The trial_id NCT004 from countries_df is not included in the result because it does not have a matching trial_id in trials_df.

left_merged_df = trials_df.merge(
    countries_df,
    on="trial_id",
    how="left"
)

left_merged_df

  trial_id sponsor_name         country
0   NCT001       Pfizer  United Kingdom
1   NCT002          GSK   United States
2   NCT003  AstraZeneca             NaN

In [51]:
# Exercise 10: Read CSV and JSON


csv_df = pd.read_csv("../data/raw/01_sample_trials.csv")

csv_df

csv_df.info()

csv_df.to_json(
    "../data/raw/sample_trials.json",
    orient="records",
    indent=2
)

json_df = pd.read_json("../data/raw/sample_trials.json")

json_df

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   trial_id      3 non-null      str
 1   sponsor_name  3 non-null      str
 2   start_year    3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

  trial_id sponsor_name  start_year
0   NCT001       Pfizer        2020
1   NCT002          GSK        2021
2   NCT003  AstraZeneca        2019